[project]
name = "deadwood-bot"
dynamic = ["version"]

authors = [
    { name = "Katulos", email = "katulos@protonmail.com" },
]
description = ""
readme = "README.md"
license = {text = "BSD-3-Clause"}
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: PyPy",
]
requires-python = ">=3.9"
dependencies = [
    "aerich[toml]>=0.9.2",
    "click>=8.1.8",
    "dynaconf>=3.2.12",
    "orjson>=3.11.5",
    "rich>=14.3.2",
    "structlog>=25.5.0",
    "telethon>=1.42.0",
    "tortoise-orm>=0.25.4",
]

[tool.setuptools.dynamic]
version = {attr = "app.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
