[project]
name = "deadwood"
description = ""
keywords = []
dynamic = [ "version" ]
authors = [
    { name = "Katulos", email = "katulos@protonmail.com" }
]
maintainers = [
    { name = "Katulos", email = "katulos@protonmail.com"}
]
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet",
    "Topic :: Software Development :: User Interfaces"
]
requires-python = ">= 3.10"
dependencies = [
    "aerich[toml]>=0.9.2",
    "aiohttp>=3.13.3",
    "asyncpraw>=7.8.1",
    "cashews[diskcache]>=7.4.4",
    "click>=8.3.1",
    "dynaconf>=3.2.12",
    "orjson>=3.11.7",
    "python-socks[asyncio]>=3.0.0",
    "rich>=14.3.2",
    "structlog>=25.5.0",
    "telethon>=1.42.0",
    "tortoise-orm>=0.25.4",
]

[tool.setuptools.dynamic]
version = {attr = "deadwood.__version__"}

[project.scripts]
deadwood = "deadwood.cli.commands:cli"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.aerich]
tortoise_orm = "deadwood.adapters.db.TORTOISE_ORM"
location = "./src/deadwood/adapters/db/migrations"
src_folder = "./."
