"""Initial.

Revision ID: 56e4753ea03f
Revises:
Create Date: 2026-09-07 14:13:26.574554

"""

import typing as t

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "56e4753ea03f"
down_revision: str | None = None
branch_labels: str | t.Sequence[str] | None = None
depends_on: str | t.Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("chat_title", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__chats")),
        sa.UniqueConstraint("chat_id", name=op.f("uq__chats__chat_id")),
    )
    op.drop_table("chat")
    op.drop_table("chat_flag")
    op.drop_table("aerich")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aerich",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("version", sa.VARCHAR(length=255), nullable=False),
        sa.Column("app", sa.VARCHAR(length=100), nullable=False),
        sa.Column("content", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_flag",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column(
            "enabled",
            sa.INTEGER(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("chat_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("chat_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "chat_title",
            sa.VARCHAR(length=128),
            server_default=sa.text("'False'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
    )
    op.drop_table("chats")
    # ### end Alembic commands ###
