name: Deploy

on:
  push:
    branches:
      - develop
      - dev
#
#    branches:
#      - master
#      - main
#      - 'releases/**'
#      - '!releases/**-alpha'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H_%M_%S')" >> $GITHUB_OUTPUT
    - uses: DamianReeves/write-file-action@master
      with:
        path: ${{ secrets.REMOTE_TARGET }}/.env
        contents: |
          API_ID=${{ secrets.API_ID }}
          API_HASH=${{ secrets.API_HASH }}
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          PHONE=${{ secrets.PHONE }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          REDIS_URL=${{ secrets.REDIS_URL }}
        write-mode: overwrite
    - name: Replace systemd unit file
      uses: datamonsters/replace-action@master
      with:
        files: 'deadwood-bot.service'
        replacements: '$REMOTE_TARGET=${{ secrets.REMOTE_TARGET }}'
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/venv/, /.venv/, /.git/, /.github/"
          # && ${{ secrets.REMOTE_TARGET }}/venv/bin/aerich upgrade
          SCRIPT_BEFORE: |
            sudo systemctl stop deadwood-bot.service
            sudo systemctl disable deadwood-bot.service
            tar --exclude='${{ secrets.REMOTE_TARGET }}/venv' -zcvf ~/deadwood-bot_backup_${{ steps.date.outputs.date }}.tgz ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            python3 -m venv ${{ secrets.REMOTE_TARGET }}/venv
            . ${{ secrets.REMOTE_TARGET }}/venv/bin/activate && ${{ secrets.REMOTE_TARGET }}/venv/bin/pip install -r ${{ secrets.REMOTE_TARGET }}/requirements.txt
            sudo ln -s ${{ secrets.REMOTE_TARGET }}/deadwood-bot.service /etc/systemd/system/deadwood-bot.service
            sudo systemctl daemon-reload
            sudo systemctl enable deadwood-bot.service
            sudo systemctl start deadwood-bot.service
