name: Deploy

on:
  push:
    branches:
      - develop
      - dev
#
#    branches:
#      - master
#      - main
#      - 'releases/**'
#      - '!releases/**-alpha'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H_%M_%S')" >> $GITHUB_OUTPUT
#    - name: Backup
#      uses: appleboy/ssh-action@v0.1.7
#      with:
#        host: ${{ secrets.REMOTE_HOST }}
#        username: ${{ secrets.REMOTE_USER }}
#        key: ${{ secrets.SSH_PRIVATE_KEY }}
#        port: ${{ secrets.REMOTE_PORT }}
#        script: |
#          sudo systemctl stop deadwood-bot.service
#          sudo systemctl disable deadwood-bot.service
#          tar -cf ~/deadwood-bot_backup_${{ steps.date.outputs.date }}.tar ${{ secrets.REMOTE_TARGET }}
#      continue-on-error: true
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/venv/, /.venv/, /.git/, /.github/"
          SCRIPT_BEFORE: |
            sudo systemctl stop deadwood-bot.service
            sudo systemctl disable deadwood-bot.service
            cd ${{ secrets.REMOTE_TARGET }} && tar --exclude='./venv' -zcvf ~/deadwood-bot_backup_${{ steps.date.outputs.date }}.tgz ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            python3 -m venv ${{ secrets.REMOTE_TARGET }}/venv
            . ${{ secrets.REMOTE_TARGET }}/venv/bin/activate && ${{ secrets.REMOTE_TARGET }}/venv/bin/pip install -r ${{ secrets.REMOTE_TARGET }}/requirements.txt && ${{ secrets.REMOTE_TARGET }}/venv/bin/aerich upgrade
            sudo ln -s ${{ secrets.REMOTE_TARGET }}/deadwood-bot.service /etc/systemd/system/deadwood-bot.service
            sudo systemctl daemon-reload
            sudo systemctl enable deadwood-bot.service
            sudo systemctl start deadwood-bot.service
#    - name: Run service
#      uses: appleboy/ssh-action@v0.1.7
#      with:
#        host: ${{ secrets.REMOTE_HOST }}
#        username: ${{ secrets.REMOTE_USER }}
#        key: ${{ secrets.SSH_PRIVATE_KEY }}
#        port: ${{ secrets.REMOTE_PORT }}
#        script: |
#          python3 -m venv ${{ secrets.REMOTE_TARGET }}/venv
#          . ${{ secrets.REMOTE_TARGET }}/venv/bin/activate && pip install -r ${{ secrets.REMOTE_TARGET }}/requirements.txt && aerich upgrade
#          sudo ln -s ${{ secrets.REMOTE_TARGET }}/deadwood-bot.service /etc/systemd/system/deadwood-bot.service
#          sudo systemctl daemon-reload
#          sudo systemctl enable deadwood-bot.service
#          sudo systemctl start deadwood-bot.service
